// Lista de certificados e cursos
const certificados = [
  { nome: "Curso de HTML e CSS", instituicao: "Alura", ano: 2023, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Introdução ao JavaScript", instituicao: "Alura", ano: 2023, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Boas Práticas em Python", instituicao: "DIO.", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Git e GitHub", instituicao: "DIO", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Cire um site completo com HTML, CSS e JavaScript", instituicao: "Udemy", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Desenvolvimento Android Completo 2024 - Kotlin & Java", instituicao: "Udemy", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Banco de Dados Relacionais com Python DB API", instituicao: "DIO", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Formação Github Certification", instituicao: "DIO", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Curso HTML e CSS", instituicao: "DIO", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Java: Primeira aplicação", instituicao: "Alura", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Bootcamp DIO: Educação e Empregabilidade", instituicao: "DIO", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Bootcamp Dio .pdf" },
  { nome: "Java: Trabalhando com listas e Coleções de Dados", instituicao: "Alura", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Curso de modelagem de dados: Entidades, Relacionamentos e Atributos", instituicao: "Alura", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Python: Avançando na Linguagem", instituicao: "DIO", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Pyhon: Orientação a Objetos", instituicao: "Alura", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Utilizando as Ferramentas do Github para solucionar Algoritmos em Python", instituicao: "DIO", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Boas Práticas em Python: Pacotes, Banco de Dados e Desenvolvimento Web", instituicao: "DIO", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
  { nome: "Desenvolvimento de APIS em Python com Flask", instituicao: "DIO", ano: 2024, url: "public/assets/pdfs/Richard Esley Silva Oliveira - Curso Administração do Github.pdf" },
];